apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata: # kpt-merge: /example
  name: regiona2
  annotations:
    internal.kpt.dev/upstream-identifier: 'infra.nephio.org|WorkloadCluster|default|example'
spec:
  # Since injection only injects the spec, we need the name here as
  # well as in metadata.
  clusterName: regiona2
  cnis:
  - macvlan
  - ipvlan
  - sriov
  masterInterface: eth1
