apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata: # kpt-merge: config-management-system/example-cluster-name
  name: regional32
  namespace: config-management-system
  annotations:
    internal.kpt.dev/upstream-identifier: configsync.gke.io|RootSync|config-management-system|example-cluster-name
    nephio.org/cluster-name: regional32
spec:
  sourceFormat: unstructured
  git:
    repo: http://172.18.0.200:3000/nephio/regional32.git
    branch: main
    auth: token
    secretRef:
      name: regional32-access-token-configsync
    period: 15s
