apiVersion: infra.nephio.org/v1alpha1
kind: Repository
metadata: # kpt-merge: default/example-cluster-name
  name: regional32
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: infra.nephio.org|Repository|default|example-cluster-name
    nephio.org/cluster-name: regional32
spec:
  description: regional32 repository
  defaultBranch: main
