apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: edge-demo
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 80
    targetPort: 5679
    nodePort: 30081
  type: NodePort
